version: '2'
services:
  redis:
    container_name: redis
    image: redis

  nginx:
    container_name: nginx
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    environment: 
        STORAGE_ADAPTER: redis
        REDIS_HOST: redisSS
        REDIS_PORT: 6379

  myapp:
    image: lidoravitan/webit-frontend

volumes:
  ssl_data: