version: '2'
services:
  redis:
    image: redis
  nginx:
    container_name: nginx
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:

  
  # your application, listening on port specified in `SITES` env variable
  myapp:
    image: lidoravitan/webit-frontend

volumes:
  ssl_data: